//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.11 at 12:13:02 PM GMT 
//


package net.oikmo.toolbox.rbxl;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.lwjgl.util.vector.Vector3f;


/**
 * <p>Java class for PropertyContainer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyContainer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{}PropertyGroup"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}Property"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyContainer", propOrder = {
		"stringOrProtectedStringOrInt"
})
@XmlSeeAlso({
	PropertyContainer.Complex.class
})
public class PropertyContainer {

	@XmlElements({
		@XmlElement(name = "string", type = PropertyContainer.String.class, nillable = true),
		@XmlElement(name = "ProtectedString", type = PropertyContainer.ProtectedString.class, nillable = true),
		@XmlElement(name = "int", type = PropertyContainer.Int.class, nillable = true),
		@XmlElement(name = "float", type = PropertyContainer.Float.class, nillable = true),
		@XmlElement(name = "double", type = PropertyContainer.Double.class, nillable = true),
		@XmlElement(name = "bool", type = PropertyContainer.Bool.class, nillable = true),
		@XmlElement(name = "token", type = PropertyContainer.Token.class, nillable = true),
		@XmlElement(name = "tokens", type = PropertyContainer.Tokens.class, nillable = true),
		@XmlElement(name = "enum", type = PropertyContainer.Enum.class, nillable = true),
		@XmlElement(name = "Ref", type = PropertyContainer.Ref.class),
		@XmlElement(name = "Refs", type = PropertyContainer.Refs.class),
		@XmlElement(name = "Vector3", type = PropertyContainer.Vector3 .class, nillable = true),
		@XmlElement(name = "CoordinateFrame", type = PropertyContainer.CoordinateFrame.class, nillable = true),
		@XmlElement(name = "Color3", type = PropertyContainer.Color3 .class, nillable = true),
		@XmlElement(name = "Complex", type = PropertyContainer.Complex.class, nillable = true),
		@XmlElement(name = "Content", type = PropertyContainer.Content.class, nillable = true)
	})
	protected List<Object> stringOrProtectedStringOrInt;
	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected java.lang.String name;

	/**
	 * Gets the value of the stringOrProtectedStringOrInt property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the stringOrProtectedStringOrInt property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getStringOrProtectedStringOrInt().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PropertyContainer.String }
	 * {@link PropertyContainer.ProtectedString }
	 * {@link PropertyContainer.Int }
	 * {@link PropertyContainer.Float }
	 * {@link PropertyContainer.Double }
	 * {@link PropertyContainer.Bool }
	 * {@link PropertyContainer.Token }
	 * {@link PropertyContainer.Tokens }
	 * {@link PropertyContainer.Enum }
	 * {@link PropertyContainer.Ref }
	 * {@link PropertyContainer.Refs }
	 * {@link PropertyContainer.Vector3 }
	 * {@link PropertyContainer.CoordinateFrame }
	 * {@link PropertyContainer.Color3 }
	 * {@link PropertyContainer.Complex }
	 * {@link PropertyContainer.Content }
	 * 
	 * 
	 */
	public List<Object> getStringOrProtectedStringOrInt() {
		if (stringOrProtectedStringOrInt == null) {
			stringOrProtectedStringOrInt = new ArrayList<Object>();
		}
		return this.stringOrProtectedStringOrInt;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link java.lang.String }
	 *     
	 */
	public java.lang.String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link java.lang.String }
	 *     
	 */
	public void setName(java.lang.String value) {
		this.name = value;
	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"value"
	})
	public static class Bool {

		@XmlValue
		protected boolean value;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the value property.
		 * 
		 */
		public boolean isValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 */
		public void setValue(boolean value) {
			this.value = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence minOccurs="0">
	 *         &lt;element name="R">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="G">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="B">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"content"
	})
	public static class Color3 {

		@XmlElementRefs({
			@XmlElementRef(name = "G", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "B", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "R", type = JAXBElement.class, required = false)
		})
		@XmlMixed
		protected List<Serializable> content;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the content property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the content property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getContent().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link JAXBElement }{@code <}{@link PropertyContainer.Color3 .B }{@code >}
		 * {@link java.lang.String }
		 * {@link JAXBElement }{@code <}{@link PropertyContainer.Color3 .G }{@code >}
		 * {@link JAXBElement }{@code <}{@link PropertyContainer.Color3 .R }{@code >}
		 * 
		 * 
		 */
		public List<Serializable> getContent() {
			if (content == null) {
				content = new ArrayList<Serializable>();
			}
			return this.content;
		}

		public long getValue() {
			return Long.parseLong((java.lang.String)content.get(0));
		}

		public int getRed() {
			int red;
			if((int)((getValue() >> 16) & 0xFF) == 0) {
				red = 0;
			} else {
				red = (int)((getValue() >> 16) & 0xFF)-4;
			}
			return red;
		}

		public int getGreen() {
			int greem;
			if((int)((getValue() >> 8) & 0xFF) == 0) {
				greem = 0;
			} else {
				greem = (int)((getValue() >> 8) & 0xFF)-4;
			}
			return greem;
		}

		public int getBlue() {
			int blue;
			if((int)(getValue() & 0xFF) == 0) {
				blue = 0;
			} else {
				blue = (int)(getValue() & 0xFF)-4;
			}
			return blue;
		}

		public java.lang.String toString() {
			return "Color3[red="+getRed()+" green="+getGreen()+" blue="+getBlue()+"]";
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class B {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class G {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class R {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;extension base="{}PropertyContainer">
	 *     &lt;/extension>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class Complex
	extends PropertyContainer
	{


	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;choice minOccurs="0">
	 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="hash" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN"/>
	 *         &lt;element name="null" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *         &lt;element name="binary">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
	 *                 &lt;attribute ref="{https://www.w3.org/2005/05/xmlmime}contentType"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/choice>
	 *       &lt;attGroup ref="{}Property"/>
	 *       &lt;attribute name="mimeType" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"content"
	})
	public static class Content {

		@XmlElementRefs({
			@XmlElementRef(name = "hash", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "binary", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "null", type = JAXBElement.class, required = false),
			@XmlElementRef(name = "url", type = JAXBElement.class, required = false)
		})
		@XmlMixed
		protected List<Serializable> content;
		@XmlAttribute(name = "mimeType")
		protected java.lang.String mimeType;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the content property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the content property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getContent().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
		 * {@link JAXBElement }{@code <}{@link PropertyContainer.Content.Binary }{@code >}
		 * {@link JAXBElement }{@code <}{@link Object }{@code >}
		 * {@link java.lang.String }
		 * {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
		 * 
		 * 
		 */
		public List<Serializable> getContent() {
			if (content == null) {
				content = new ArrayList<Serializable>();
			}
			return this.content;
		}

		/**
		 * Gets the value of the mimeType property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getMimeType() {
			return mimeType;
		}

		/**
		 * Sets the value of the mimeType property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setMimeType(java.lang.String value) {
			this.mimeType = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
		 *       &lt;attribute ref="{https://www.w3.org/2005/05/xmlmime}contentType"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class Binary {

			@XmlValue
			protected byte[] value;
			@XmlAttribute(name = "contentType", namespace = "https://www.w3.org/2005/05/xmlmime")
			protected java.lang.String contentType;

			/**
			 * Gets the value of the value property.
			 * 
			 * @return
			 *     possible object is
			 *     byte[]
			 */
			public byte[] getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 * @param value
			 *     allowed object is
			 *     byte[]
			 */
			public void setValue(byte[] value) {
				this.value = value;
			}

			/**
			 * Gets the value of the contentType property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getContentType() {
				return contentType;
			}

			/**
			 * Sets the value of the contentType property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setContentType(java.lang.String value) {
				this.contentType = value;
			}

		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence minOccurs="0">
	 *         &lt;element name="X">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="Y">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="Z">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="R00">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="R01">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="R02">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="R10">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="R11">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="R12">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="R20">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="R21">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="R22">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"x",
			"y",
			"z",
			"r00",
			"r01",
			"r02",
			"r10",
			"r11",
			"r12",
			"r20",
			"r21",
			"r22"
	})
	public static class CoordinateFrame {

		@XmlElementRef(name = "X", type = JAXBElement.class, required = false)
		protected JAXBElement<PropertyContainer.CoordinateFrame.X> x;
		@XmlElementRef(name = "Y", type = JAXBElement.class, required = false)
		protected JAXBElement<PropertyContainer.CoordinateFrame.Y> y;
		@XmlElementRef(name = "Z", type = JAXBElement.class, required = false)
		protected JAXBElement<PropertyContainer.CoordinateFrame.Z> z;
		@XmlElementRef(name = "R00", type = JAXBElement.class, required = false)
		protected JAXBElement<PropertyContainer.CoordinateFrame.R00> r00;
		@XmlElementRef(name = "R01", type = JAXBElement.class, required = false)
		protected JAXBElement<PropertyContainer.CoordinateFrame.R01> r01;
		@XmlElementRef(name = "R02", type = JAXBElement.class, required = false)
		protected JAXBElement<PropertyContainer.CoordinateFrame.R02> r02;
		@XmlElementRef(name = "R10", type = JAXBElement.class, required = false)
		protected JAXBElement<PropertyContainer.CoordinateFrame.R10> r10;
		@XmlElementRef(name = "R11", type = JAXBElement.class, required = false)
		protected JAXBElement<PropertyContainer.CoordinateFrame.R11> r11;
		@XmlElementRef(name = "R12", type = JAXBElement.class, required = false)
		protected JAXBElement<PropertyContainer.CoordinateFrame.R12> r12;
		@XmlElementRef(name = "R20", type = JAXBElement.class, required = false)
		protected JAXBElement<PropertyContainer.CoordinateFrame.R20> r20;
		@XmlElementRef(name = "R21", type = JAXBElement.class, required = false)
		protected JAXBElement<PropertyContainer.CoordinateFrame.R21> r21;
		@XmlElementRef(name = "R22", type = JAXBElement.class, required = false)
		protected JAXBElement<PropertyContainer.CoordinateFrame.R22> r22;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the x property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.X }{@code >}
		 *     
		 */
		public JAXBElement<PropertyContainer.CoordinateFrame.X> getX() {
			return x;
		}

		public float x() {
			return getX().getValue().getValue();
		}

		/**
		 * Sets the value of the x property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.X }{@code >}
		 *     
		 */
		public void setX(JAXBElement<PropertyContainer.CoordinateFrame.X> value) {
			this.x = value;
		}
		public void x(float value) {
			getX().getValue().setValue(value);
		}

		/**
		 * Gets the value of the y property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.Y }{@code >}
		 *     
		 */
		public JAXBElement<PropertyContainer.CoordinateFrame.Y> getY() {
			return y;
		}
		public float y() {
			return getY().getValue().getValue();
		}

		/**
		 * Sets the value of the y property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.Y }{@code >}
		 *     
		 */
		public void setY(JAXBElement<PropertyContainer.CoordinateFrame.Y> value) {
			this.y = value;
		}
		public void y(float value) {
			getY().getValue().setValue(value);
		}


		/**
		 * Gets the value of the z property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.Z }{@code >}
		 *     
		 */
		public JAXBElement<PropertyContainer.CoordinateFrame.Z> getZ() {
			return z;
		}
		public float z() {
			return getZ().getValue().getValue();
		}

		/**
		 * Sets the value of the z property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.Z }{@code >}
		 *     
		 */
		public void setZ(JAXBElement<PropertyContainer.CoordinateFrame.Z> value) {
			this.z = value;
		}
		public void z(float value) {
			getZ().getValue().setValue(value);
		}

		/**
		 * Gets the value of the r00 property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R00 }{@code >}
		 *     
		 */
		public JAXBElement<PropertyContainer.CoordinateFrame.R00> getR00() {
			return r00;
		}

		/**
		 * Sets the value of the r00 property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R00 }{@code >}
		 *     
		 */
		public void setR00(JAXBElement<PropertyContainer.CoordinateFrame.R00> value) {
			this.r00 = value;
		}

		/**
		 * Gets the value of the r01 property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R01 }{@code >}
		 *     
		 */
		public JAXBElement<PropertyContainer.CoordinateFrame.R01> getR01() {
			return r01;
		}

		/**
		 * Sets the value of the r01 property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R01 }{@code >}
		 *     
		 */
		public void setR01(JAXBElement<PropertyContainer.CoordinateFrame.R01> value) {
			this.r01 = value;
		}

		/**
		 * Gets the value of the r02 property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R02 }{@code >}
		 *     
		 */
		public JAXBElement<PropertyContainer.CoordinateFrame.R02> getR02() {
			return r02;
		}

		/**
		 * Sets the value of the r02 property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R02 }{@code >}
		 *     
		 */
		public void setR02(JAXBElement<PropertyContainer.CoordinateFrame.R02> value) {
			this.r02 = value;
		}

		/**
		 * Gets the value of the r10 property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R10 }{@code >}
		 *     
		 */
		public JAXBElement<PropertyContainer.CoordinateFrame.R10> getR10() {
			return r10;
		}

		/**
		 * Sets the value of the r10 property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R10 }{@code >}
		 *     
		 */
		public void setR10(JAXBElement<PropertyContainer.CoordinateFrame.R10> value) {
			this.r10 = value;
		}

		/**
		 * Gets the value of the r11 property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R11 }{@code >}
		 *     
		 */
		public JAXBElement<PropertyContainer.CoordinateFrame.R11> getR11() {
			return r11;
		}

		/**
		 * Sets the value of the r11 property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R11 }{@code >}
		 *     
		 */
		public void setR11(JAXBElement<PropertyContainer.CoordinateFrame.R11> value) {
			this.r11 = value;
		}

		/**
		 * Gets the value of the r12 property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R12 }{@code >}
		 *     
		 */
		public JAXBElement<PropertyContainer.CoordinateFrame.R12> getR12() {
			return r12;
		}

		/**
		 * Sets the value of the r12 property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R12 }{@code >}
		 *     
		 */
		public void setR12(JAXBElement<PropertyContainer.CoordinateFrame.R12> value) {
			this.r12 = value;
		}

		/**
		 * Gets the value of the r20 property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R20 }{@code >}
		 *     
		 */
		public JAXBElement<PropertyContainer.CoordinateFrame.R20> getR20() {
			return r20;
		}

		/**
		 * Sets the value of the r20 property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R20 }{@code >}
		 *     
		 */
		public void setR20(JAXBElement<PropertyContainer.CoordinateFrame.R20> value) {
			this.r20 = value;
		}

		/**
		 * Gets the value of the r21 property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R21 }{@code >}
		 *     
		 */
		public JAXBElement<PropertyContainer.CoordinateFrame.R21> getR21() {
			return r21;
		}

		/**
		 * Sets the value of the r21 property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R21 }{@code >}
		 *     
		 */
		public void setR21(JAXBElement<PropertyContainer.CoordinateFrame.R21> value) {
			this.r21 = value;
		}

		/**
		 * Gets the value of the r22 property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R22 }{@code >}
		 *     
		 */
		public JAXBElement<PropertyContainer.CoordinateFrame.R22> getR22() {
			return r22;
		}

		/**
		 * Sets the value of the r22 property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link JAXBElement }{@code <}{@link PropertyContainer.CoordinateFrame.R22 }{@code >}
		 *     
		 */
		public void setR22(JAXBElement<PropertyContainer.CoordinateFrame.R22> value) {
			this.r22 = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}



		//I give all my kudos to that one stack overflow post I found (that was in c++)
		/**
		 * Returns rotational values from the CFrame matrix
		 * @author stack overflow (my beloved)
		 */
		public Vector3f getAngles() {
			double RADTODEG = 180.0 / Math.PI;
			double EPS = 1.0e-6;
			double X, Y, Z;

			Y = Math.asin(r02.getValue().getValue());                       // Unique angle in [-pi/2,pi/2]

			if (Math.abs(Math.abs(r02.getValue().getValue()) - 1.0) < EPS) { // Yuk! Gimbal lock. Infinite choice of X and Z
				X = Math.atan2(r21.getValue().getValue(), r11.getValue().getValue());          // One choice amongst many
				Z = 0.0;
			} else {                                   // Unique solutions in (-pi,pi]
				X = Math.atan2(-r12.getValue().getValue(), r22.getValue().getValue());         // atan2 gives correct quadrant and unique solutions
				Z = Math.atan2(-r01.getValue().getValue(), r00.getValue().getValue());
			}

			X *= RADTODEG;   
			Y *= RADTODEG;   
			Z *= RADTODEG;

			return new Vector3f((float)X,(float)Y,(float)Z);
		}

		public java.lang.String toString() {
			return "cframe[x="+x()+", y="+y()+", z"+z()+"]";
		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class R00 {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class R01 {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class R02 {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class R10 {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class R11 {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class R12 {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class R20 {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class R21 {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class R22 {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class X {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class Y {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class Z {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"value"
	})
	public static class Double {

		@XmlValue
		protected double value;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the value property.
		 * 
		 */
		public double getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 */
		public void setValue(double value) {
			this.value = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>unsignedShort">
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"value"
	})
	public static class Enum {

		@XmlValue
		@XmlSchemaType(name = "unsignedShort")
		protected int value;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the value property.
		 * 
		 */
		public int getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 */
		public void setValue(int value) {
			this.value = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"value"
	})
	public static class Float {

		@XmlValue
		protected float value;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the value property.
		 * 
		 */
		public float getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 */
		public void setValue(float value) {
			this.value = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"value"
	})
	public static class Int {

		@XmlValue
		protected int value;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the value property.
		 * 
		 */
		public int getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 */
		public void setValue(int value) {
			this.value = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"value"
	})
	public static class ProtectedString {

		@XmlValue
		protected java.lang.String value;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setValue(java.lang.String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>IDREF">
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"value"
	})
	public static class Ref {

		@XmlValue
		@XmlIDREF
		@XmlSchemaType(name = "IDREF")
		protected Object value;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Object }
		 *     
		 */
		public Object getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Object }
		 *     
		 */
		public void setValue(Object value) {
			this.value = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>IDREFS">
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"value"
	})
	public static class Refs {

		@XmlValue
		@XmlIDREF
		@XmlSchemaType(name = "IDREFS")
		protected List<Object> value;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the value property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the value property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getValue().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Object }
		 * 
		 * 
		 */
		public List<Object> getValue() {
			if (value == null) {
				value = new ArrayList<Object>();
			}
			return this.value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"value"
	})
	public static class String {

		@XmlValue
		protected java.lang.String value;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setValue(java.lang.String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKEN">
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"value"
	})
	public static class Token {

		@XmlValue
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String value;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setValue(java.lang.String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKENS">
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"value"
	})
	public static class Tokens {

		@XmlValue
		@XmlSchemaType(name = "NMTOKENS")
		protected List<java.lang.String> value;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the value property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the value property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getValue().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link java.lang.String }
		 * 
		 * 
		 */
		public List<java.lang.String> getValue() {
			if (value == null) {
				value = new ArrayList<java.lang.String>();
			}
			return this.value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}

	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="X">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="Y">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="Z">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
	 *                 &lt;attGroup ref="{}Referent"/>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attGroup ref="{}Property"/>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"x",
			"y",
			"z"
	})
	public static class Vector3 {

		@XmlElement(name = "X", required = true, nillable = true)
		protected PropertyContainer.Vector3 .X x;
		@XmlElement(name = "Y", required = true, nillable = true)
		protected PropertyContainer.Vector3 .Y y;
		@XmlElement(name = "Z", required = true, nillable = true)
		protected PropertyContainer.Vector3 .Z z;
		@XmlAttribute(name = "name", required = true)
		@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
		@XmlSchemaType(name = "NMTOKEN")
		protected java.lang.String name;

		/**
		 * Gets the value of the x property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link PropertyContainer.Vector3 .X }
		 *     
		 */
		public float getX() {
			return x.getValue();
		}

		/**
		 * Sets the value of the x property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link PropertyContainer.Vector3 .X }
		 *     
		 */
		public void setX(float value) {
			this.x.setValue(value);
		}

		/**
		 * Gets the value of the y property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link PropertyContainer.Vector3 .Y }
		 *     
		 */
		public float getY() {
			return y.getValue();
		}

		/**
		 * Sets the value of the y property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link PropertyContainer.Vector3 .Y }
		 *     
		 */
		public void setY(float value) {
			this.y.setValue(value);
		}

		/**
		 * Gets the value of the z property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link PropertyContainer.Vector3 .Z }
		 *     
		 */
		public float getZ() {
			return z.getValue();
		}

		/**
		 * Sets the value of the z property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link PropertyContainer.Vector3 .Z }
		 *     
		 */
		public void setZ(float value) {
			this.z.setValue(value);
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link java.lang.String }
		 *     
		 */
		public java.lang.String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link java.lang.String }
		 *     
		 */
		public void setName(java.lang.String value) {
			this.name = value;
		}

		public java.lang.String toString() {
			return "vector3[x="+ getX() +", y=" + getY() + ", z="+getZ()+"]";
		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class X {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class Y {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}


		/**
		 * <p>Java class for anonymous complex type.
		 * 
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
		 *       &lt;attGroup ref="{}Referent"/>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class Z {

			@XmlValue
			protected float value;
			@XmlAttribute(name = "referent")
			@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
			@XmlID
			@XmlSchemaType(name = "ID")
			protected java.lang.String referent;

			/**
			 * Gets the value of the value property.
			 * 
			 */
			public float getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 */
			public void setValue(float value) {
				this.value = value;
			}

			/**
			 * Gets the value of the referent property.
			 * 
			 * @return
			 *     possible object is
			 *     {@link java.lang.String }
			 *     
			 */
			public java.lang.String getReferent() {
				return referent;
			}

			/**
			 * Sets the value of the referent property.
			 * 
			 * @param value
			 *     allowed object is
			 *     {@link java.lang.String }
			 *     
			 */
			public void setReferent(java.lang.String value) {
				this.referent = value;
			}

		}

	}

}
