//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.11 at 12:13:02 PM GMT 
//


package net.pepdog.toolbox.rbxl;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemType", propOrder = {
		"properties",
		"item"
})
@XmlSeeAlso({
	Item.class
})
public class ItemType {

	@XmlElement(name = "Properties", required = true)
	protected ItemType.Properties properties;
	@XmlElement(name = "Item")
	protected List<Item> item;
	@XmlAttribute(name = "class", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String clazz;
	@XmlAttribute(name = "referent")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlID
	@XmlSchemaType(name = "ID")
	protected String referent;

	/**
	 * Gets the value of the properties property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link ItemType.Properties }
	 *     
	 */
	public ItemType.Properties getProperties() {
		return properties;
	}

	/**
	 * Sets the value of the properties property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link ItemType.Properties }
	 *     
	 */
	public void setProperties(ItemType.Properties value) {
		this.properties = value;
	}

	/**
	 * Gets the value of the item property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the item property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getItem().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Item }
	 * 
	 * 
	 */
	public List<Item> getItem() {
		if (item == null) {
			item = new ArrayList<Item>();
		}
		return this.item;
	}

	/**
	 * Gets the value of the clazz property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getClazz() {
		return clazz;
	}

	/**
	 * Sets the value of the clazz property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setClazz(String value) {
		this.clazz = value;
	}

	/**
	 * Gets the value of the referent property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getReferent() {
		return referent;
	}

	/**
	 * Sets the value of the referent property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setReferent(String value) {
		this.referent = value;
	}
	
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"stringOrProtectedStringOrInt"
	})
	public static class Properties {

		@XmlElements({
			@XmlElement(name = "string", type = PropertyContainer.String.class, nillable = true),
			@XmlElement(name = "ProtectedString", type = PropertyContainer.ProtectedString.class, nillable = true),
			@XmlElement(name = "int", type = PropertyContainer.Int.class, nillable = true),
			@XmlElement(name = "float", type = PropertyContainer.Float.class, nillable = true),
			@XmlElement(name = "double", type = PropertyContainer.Double.class, nillable = true),
			@XmlElement(name = "bool", type = PropertyContainer.Bool.class, nillable = true),
			@XmlElement(name = "token", type = PropertyContainer.Token.class, nillable = true),
			@XmlElement(name = "tokens", type = PropertyContainer.Tokens.class, nillable = true),
			@XmlElement(name = "enum", type = PropertyContainer.Enum.class, nillable = true),
			@XmlElement(name = "Ref", type = PropertyContainer.Ref.class),
			@XmlElement(name = "Refs", type = PropertyContainer.Refs.class),
			@XmlElement(name = "Vector3", type = PropertyContainer.Vector3 .class, nillable = true),
			@XmlElement(name = "CoordinateFrame", type = PropertyContainer.CoordinateFrame.class, nillable = true),
			@XmlElement(name = "Color3", type = PropertyContainer.Color3 .class, nillable = true),
			@XmlElement(name = "Complex", type = PropertyContainer.Complex.class, nillable = true),
			@XmlElement(name = "Content", type = PropertyContainer.Content.class, nillable = true),
			@XmlElement(name = "Feature", type = PropertyContainer.class)
		})
		protected List<Object> stringOrProtectedStringOrInt;

		/**
		 * Gets the value of the stringOrProtectedStringOrInt property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the stringOrProtectedStringOrInt property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getStringOrProtectedStringOrInt().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link PropertyContainer.String }
		 * {@link PropertyContainer.ProtectedString }
		 * {@link PropertyContainer.Int }
		 * {@link PropertyContainer.Float }
		 * {@link PropertyContainer.Double }
		 * {@link PropertyContainer.Bool }
		 * {@link PropertyContainer.Token }
		 * {@link PropertyContainer.Tokens }
		 * {@link PropertyContainer.Enum }
		 * {@link PropertyContainer.Ref }
		 * {@link PropertyContainer.Refs }
		 * {@link PropertyContainer.Vector3 }
		 * {@link PropertyContainer.CoordinateFrame }
		 * {@link PropertyContainer.Color3 }
		 * {@link PropertyContainer.Complex }
		 * {@link PropertyContainer.Content }
		 * {@link PropertyContainer }
		 * 
		 * 
		 */
		public List<Object> getStringOrProtectedStringOrInt() {
			if (stringOrProtectedStringOrInt == null) {
				stringOrProtectedStringOrInt = new ArrayList<Object>();
			}
			return this.stringOrProtectedStringOrInt;
		}

	}

}
